{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mitsuki.armory",
    "module": "imagegesture",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "imagegesture-1.0.1.aar",
          "url": "imagegesture-1.0.1.aar",
          "size": 15714,
          "sha512": "56308f99bc0d74e957d792e59f8673fa4b2b7b3374d13942fa805c1aaa5bd0da7d362386906933f6652b4876871eb1fd988f072624ed5c0a20e27be87db32dee",
          "sha256": "e3042e60b4f5eb20318926934ab0f5b1fcf94994f40c2cea2a95245b4a56135d",
          "sha1": "e809be1cbc6a411c26447179be18f71cb6270fc7",
          "md5": "a3a5548eae319e7806436e57991cfaac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "imagegesture-1.0.1.aar",
          "url": "imagegesture-1.0.1.aar",
          "size": 15714,
          "sha512": "56308f99bc0d74e957d792e59f8673fa4b2b7b3374d13942fa805c1aaa5bd0da7d362386906933f6652b4876871eb1fd988f072624ed5c0a20e27be87db32dee",
          "sha256": "e3042e60b4f5eb20318926934ab0f5b1fcf94994f40c2cea2a95245b4a56135d",
          "sha1": "e809be1cbc6a411c26447179be18f71cb6270fc7",
          "md5": "a3a5548eae319e7806436e57991cfaac"
        }
      ]
    }
  ]
}
